In [1]:
import torch
from torch import Tensor, optim
from torch.autograd import Variable

In [2]:
dtype = torch.float32

In [3]:
def linear_model(x:Tensor, w:Tensor) -> Tensor:
    return torch.matmul(x, w)

dim_model = 2

w = Variable(torch.tensor([[-1, 1], [-2, 2]], dtype=dtype), requires_grad=True)

data = torch.tensor([1, 2], dtype=dtype)
target = torch.tensor([0, 1], dtype=dtype)

print(w)

tensor([[-1.,  1.],
        [-2.,  2.]], requires_grad=True)


In [55]:
# SGD

learning_rate = 0.1

#w.grad.data.zero_()

output = linear_model(data, w)
loss = (output - target).sum()
print(loss)

loss.backward()

print(loss)
print(w)
print(w.grad)

#w -= learning_rate * w.grad.data

tensor(-1., grad_fn=<SumBackward0>)
tensor(-1., grad_fn=<SumBackward0>)
tensor([[-1.,  1.],
        [-2.,  2.]], requires_grad=True)
tensor([[ 51.,  51.],
        [102., 102.]])


In [5]:
# Adam

# optimizer = optim.Adam([w])

# for sample, target in zip(data, targets):
#     # clear out the gradients of all Variables
#     optimizer.zero_grad()

#     output = linear_model(sample, w)
#     loss = (output - target) ** 2
#     loss.backward()

#     optimizer.step()