In [1]:
import numpy as np
import torch
from pathlib import Path

In [2]:
path = Path.cwd() / ".." / "data" / "shakespeare_char" / "train.bin"
data = np.memmap(path, dtype=np.uint16, mode="r")

print(len(data))

1003854


In [3]:
batch_size = 4
seq_len = 8

num_seq = (len(data) - 1) // seq_len

last_idx = num_seq * seq_len


In [4]:
torch.randint(len(data) - seq_len, (batch_size,))

tensor([505562, 372919, 121209, 869482])

In [5]:
for i in range(3):
    #i = [i for i in torch.arange(0, batch_size).reshape((batch_size, ))]
    ix = torch.randint(len(data) - seq_len, (batch_size,))
    t = torch.stack([torch.from_numpy((data[i : i + seq_len]).astype(np.int64)) for i in ix])
    print(i, ix)
    print(t)

0 tensor([452358, 297687, 133625, 894345])
tensor([[61, 47, 50, 50,  1, 57, 58, 47],
        [ 1, 58, 46, 43,  1, 46, 39, 59],
        [ 1, 46, 43, 39, 56,  1, 58, 46],
        [42, 43, 56,  1, 42, 53, 61, 52]])
1 tensor([971480, 465743, 559762, 952115])
tensor([[44,  1, 58, 46, 43,  1, 40, 53],
        [47, 57,  1, 39, 52,  1, 43, 51],
        [58, 43, 56,  5, 42,  6,  1, 58],
        [47, 51, 39, 45, 47, 52, 43, 42]])
2 tensor([696522, 140070, 262360, 519278])
tensor([[39, 60, 43,  1, 57, 39, 60, 43],
        [50, 58,  1, 52, 53, 58,  7,  7],
        [ 1, 58, 46, 53, 59,  1, 47, 52],
        [39, 56, 49,  1, 63, 43,  6,  1]])
