In [1]:
import torch
from torch import Tensor
from torch.nn import Linear

In [2]:
n_batch = 2
n_token = 5
dim_model = 4
total_len = n_batch*n_token*dim_model
a = torch.arange(total_len, dtype=torch.float32).reshape((n_batch, n_token, dim_model))
#print(a.shape)
B, T, C = a.shape
print(B, T, C)
a

2 5 4


tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]],

        [[20., 21., 22., 23.],
         [24., 25., 26., 27.],
         [28., 29., 30., 31.],
         [32., 33., 34., 35.],
         [36., 37., 38., 39.]]])

In [3]:
c_attn = Linear(dim_model, 3 * dim_model)

b = c_attn(a).round()
print(b.shape)
#b

torch.Size([2, 5, 12])


In [4]:
q, k, v = b.split(dim_model, dim=-1)
print(q.shape, k.shape, v.shape)
q, k, v

torch.Size([2, 5, 4]) torch.Size([2, 5, 4]) torch.Size([2, 5, 4])


(tensor([[[ -1.,  -1.,   2.,  -2.],
          [ -3.,  -3.,   3.,  -6.],
          [ -6.,  -5.,   5.,  -9.],
          [ -8.,  -6.,   6., -13.],
          [-11.,  -8.,   8., -16.]],
 
         [[-13., -10.,   9., -20.],
          [-15., -11.,  11., -24.],
          [-18., -13.,  12., -27.],
          [-20., -15.,  14., -31.],
          [-23., -16.,  16., -35.]]], grad_fn=<SplitBackward0>),
 tensor([[[ -0.,  -2.,  -1.,  -0.],
          [ -1.,  -5.,  -1.,  -0.],
          [ -1.,  -8.,  -1.,   0.],
          [ -1., -11.,  -0.,   0.],
          [ -1., -14.,   0.,   1.]],
 
         [[ -1., -17.,   0.,   1.],
          [ -2., -20.,   1.,   1.],
          [ -2., -23.,   1.,   1.],
          [ -2., -26.,   1.,   1.],
          [ -2., -29.,   2.,   2.]]], grad_fn=<SplitBackward0>),
 tensor([[[  1.,  -0.,   1.,  -1.],
          [  0.,  -2.,   2.,   1.],
          [ -1.,  -3.,   3.,   3.],
          [ -2.,  -4.,   4.,   4.],
          [ -2.,  -5.,   5.,   6.]],
 
         [[ -3.,  -7.,   6.,   8.

In [5]:
m = torch.tril(torch.ones((4,4)), diagonal=-1)
m

tensor([[0., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 1., 0., 0.],
        [1., 1., 1., 0.]])

In [6]:
m.transpose(-2, -1)

tensor([[0., 1., 1., 1.],
        [0., 0., 1., 1.],
        [0., 0., 0., 1.],
        [0., 0., 0., 0.]])

In [14]:
n = torch.ones((2,3,4,5))
print(n.shape[-1:])
n

torch.Size([5])


tensor([[[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]],


        [[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]]])