In [1]:
import torch

In [2]:
width = 3
height = 4

In [3]:
x = torch.arange(height, dtype=torch.float32)+1
x

tensor([1., 2., 3., 4.])

In [4]:
W = torch.arange(width*height, dtype=torch.float32).reshape((width, height))
W

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [5]:
W @ x

tensor([ 20.,  60., 100.])

In [6]:
x @ W.T

tensor([ 20.,  60., 100.])

In [7]:
torch.matmul(x, W.T)

tensor([ 20.,  60., 100.])